language: dita
install:
  - echo "Installed"
script:
  - sh .travis/publish.sh
after_success:
  - sh .travis/deploy.sh
env:
  global:
    - DITAMAP=dita/garage/garage.ditamap
    - OPT_DIR=publishing/material/
    - OPT_FILE=material.opt
    - ANT_OPTS=-Xmx1024M
    - OUT_DIR=output
    - TEMP_DIR=temp
before_install:
  - chmod +x .travis/publish.sh
  - chmod +x tools/oxygen-publishing-engine-3.x/bin/dita
  - chmod +x .travis/deploy.sh
    
    